ALTER TABLE "Product"
ADD COLUMN IF NOT EXISTS "thcPercent" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "cbdPercent" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "cbdMgPerUnit" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "thcMgPerUnit" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "weight" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "labTestUrl" TEXT;
