DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'OrderPaymentMethod') THEN
        CREATE TYPE "OrderPaymentMethod" AS ENUM ('pay_at_pickup', 'card');
    END IF;
END $$;

ALTER TABLE "Order"
ADD COLUMN IF NOT EXISTS "paymentMethod" "OrderPaymentMethod" NOT NULL DEFAULT 'pay_at_pickup',
ADD COLUMN IF NOT EXISTS "notes" TEXT,
ADD COLUMN IF NOT EXISTS "contactName" TEXT,
ADD COLUMN IF NOT EXISTS "contactPhone" TEXT,
ADD COLUMN IF NOT EXISTS "contactEmail" TEXT,
ADD COLUMN IF NOT EXISTS "subtotal" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "tax" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "discount" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "deliveryFee" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "tipAmount" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "deliveryAddress" TEXT,
ADD COLUMN IF NOT EXISTS "deliveryNotes" TEXT,
ADD COLUMN IF NOT EXISTS "scheduledFor" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "completedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "cancelledAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "cancelReason" TEXT;
