-- Add missing Store columns
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "logoUrl" TEXT;
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "bannerUrl" TEXT;
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "hours" JSONB;
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "licenseNumber" TEXT;
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "licenseExpiry" TIMESTAMP(3);
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "avgRating" DOUBLE PRECISION;
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "reviewCount" INTEGER;
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;

-- CreateIndex
CREATE INDEX IF NOT EXISTS "Store_isActive_idx" ON "Store"("isActive");
CREATE INDEX IF NOT EXISTS "Store_brandId_idx" ON "Store"("brandId");
