import { createClient } from "@sanity/client";

function required(name: string): string {
  const v = process.env[name];
  if (!v) throw new Error(`Missing ${name}`);
  return v;
}

function pick(...names: string[]): string | undefined {
  for (const n of names) {
    const v = process.env[n];
    if (v) return v;
  }
  return undefined;
}

function portableTextFromMarkdownTitleAndBody(title: string, body: string) {
  // Minimal Portable Text: one heading + one paragraph.
  return [
    {
      _type: "block",
      style: "h2",
      children: [{ _type: "span", text: title }],
      markDefs: [],
    },
    {
      _type: "block",
      style: "normal",
      children: [{ _type: "span", text: body }],
      markDefs: [],
    },
  ];
}

async function main() {
  const projectId = pick("SANITY_PROJECT_ID", "SANITY_STUDIO_PROJECT_ID")!;
  const dataset = pick("SANITY_DATASET", "SANITY_STUDIO_DATASET") || "nimbus_demo";
  const token =
    pick("SANITY_API_TOKEN", "SANITY_WRITE_TOKEN", "SANITY_AUTH_TOKEN", "SANITY_TOKEN") ||
    required("SANITY_PREVIEW_TOKEN");

  const brandRef = pick("SANITY_DEMO_BRAND_REF") || "brand-nimbus-demo";
  const storeRef = pick("SANITY_DEMO_STORE_REF") || "store-nimbus-demo-downtown";

  const client = createClient({
    projectId,
    dataset,
    apiVersion: process.env.SANITY_API_VERSION || "2023-07-01",
    token,
    useCdn: false,
  });

  const now = new Date().toISOString();

  const docs = [
    {
      _id: "tos-demo",
      _type: "legalDoc",
      title: "SAMPLE TEMPLATE – REPLACE: Terms of Service",
      type: "terms",
      version: "0.0-demo",
      effectiveFrom: now,
      body: portableTextFromMarkdownTitleAndBody(
        "SAMPLE TEMPLATE – REPLACE",
        "This is placeholder demo legal content. Replace with counsel-approved Terms of Service before production use.",
      ),
      notes: "Demo placeholder generated by scripts/sanity-seed-legal-demo.ts",
      brand: { _type: "reference", _ref: brandRef },
      stores: [{ _type: "reference", _ref: storeRef }],
    },
    {
      _id: "privacy-demo",
      _type: "legalDoc",
      title: "SAMPLE TEMPLATE – REPLACE: Privacy Policy",
      type: "privacy",
      version: "0.0-demo",
      effectiveFrom: now,
      body: portableTextFromMarkdownTitleAndBody(
        "SAMPLE TEMPLATE – REPLACE",
        "This is placeholder demo legal content. Replace with your real Privacy Policy before production use.",
      ),
      notes: "Demo placeholder generated by scripts/sanity-seed-legal-demo.ts",
      brand: { _type: "reference", _ref: brandRef },
      stores: [{ _type: "reference", _ref: storeRef }],
    },
    {
      _id: "disclaimer-demo",
      _type: "legalDoc",
      title: "SAMPLE TEMPLATE – REPLACE: Disclaimers",
      type: "disclaimer",
      version: "0.0-demo",
      effectiveFrom: now,
      body: portableTextFromMarkdownTitleAndBody(
        "SAMPLE TEMPLATE – REPLACE",
        "This is placeholder demo legal content. Replace disclaimers (age/use/medical) per jurisdiction before production use.",
      ),
      notes: "Demo placeholder generated by scripts/sanity-seed-legal-demo.ts",
      brand: { _type: "reference", _ref: brandRef },
      stores: [{ _type: "reference", _ref: storeRef }],
    },
  ];

  for (const doc of docs) {
    await client
      .transaction()
      .createOrReplace(doc as any)
      .commit({ visibility: "async" });
    // eslint-disable-next-line no-console
    console.log("Upserted", { id: doc._id, dataset });
  }
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error(err);
  process.exit(1);
});
