import { defineField, defineType } from "sanity";

export default defineType({
  name: "store",
  type: "document",
  title: "Store",
  fields: [
    defineField({ name: "name", type: "string", title: "Name" }),
    defineField({
      name: "slug",
      type: "slug",
      title: "Slug",
      options: { source: "name", maxLength: 96 },
    }),
    defineField({
      name: "brand",
      type: "reference",
      to: [{ type: "brand" }],
      title: "Brand",
    }),
    defineField({ name: "address", type: "string", title: "Address" }),
    defineField({ name: "address2", type: "string", title: "Address line 2" }),
    defineField({ name: "city", type: "string", title: "City" }),
    defineField({ name: "stateCode", type: "string", title: "State code" }),
    defineField({ name: "zip", type: "string", title: "ZIP" }),
    defineField({ name: "phone", type: "string", title: "Phone" }),
    defineField({ name: "email", type: "string", title: "Email" }),
    defineField({ name: "description", type: "text", title: "Description" }),
    defineField({ name: "country", type: "string", title: "Country" }),
    defineField({
      name: "logo",
      type: "image",
      title: "Logo",
      options: { hotspot: true },
    }),
    defineField({
      name: "banner",
      type: "image",
      title: "Banner",
      options: { hotspot: true },
    }),
    defineField({ name: "timezone", type: "string", title: "Timezone" }),
    defineField({ name: "hours", type: "object", title: "Hours", fields: [
      { name: "monday", type: "string", title: "Monday" },
      { name: "tuesday", type: "string", title: "Tuesday" },
      { name: "wednesday", type: "string", title: "Wednesday" },
      { name: "thursday", type: "string", title: "Thursday" },
      { name: "friday", type: "string", title: "Friday" },
      { name: "saturday", type: "string", title: "Saturday" },
      { name: "sunday", type: "string", title: "Sunday" },
    ] }),
    defineField({ name: "latitude", type: "number", title: "Latitude" }),
    defineField({ name: "longitude", type: "number", title: "Longitude" }),
    defineField({
      name: "isDeliveryEnabled",
      type: "boolean",
      title: "Delivery enabled",
      initialValue: false,
    }),
    defineField({
      name: "isPickupEnabled",
      type: "boolean",
      title: "Pickup enabled",
      initialValue: true,
    }),
    defineField({ name: "deliveryFee", type: "number", title: "Delivery fee" }),
    defineField({ name: "minOrderAmount", type: "number", title: "Minimum order" }),
    defineField({ name: "deliveryRadius", type: "number", title: "Delivery radius" }),
    defineField({
      name: "amenities",
      type: "array",
      title: "Amenities",
      of: [{ type: "string" }],
    }),
    defineField({ name: "licenseNumber", type: "string", title: "License number" }),
    defineField({ name: "licenseExpiry", type: "datetime", title: "License expiry" }),
    defineField({ name: "avgRating", type: "number", title: "Average rating" }),
    defineField({ name: "reviewCount", type: "number", title: "Review count" }),
    defineField({
      name: "gallery",
      type: "array",
      title: "Gallery images",
      of: [{ type: "image", options: { hotspot: true } }],
    }),
    defineField({
      name: "holidayHours",
      type: "array",
      title: "Holiday hours",
      of: [
        {
          type: "object",
          fields: [
            { name: "date", type: "date", title: "Date" },
            { name: "hours", type: "string", title: "Hours" },
            { name: "note", type: "string", title: "Note" },
          ],
        },
      ],
    }),
    defineField({ name: "orderingUrl", type: "url", title: "Online ordering URL" }),
    defineField({ name: "menuUrl", type: "url", title: "Menu URL" }),
    defineField({
      name: "complianceFlags",
      type: "array",
      title: "Compliance flags",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "isActive",
      type: "boolean",
      title: "Is active",
      initialValue: true,
    }),
  ],
  preview: {
    select: { title: "name" },
  },
});
