-- CreateTable
CREATE TABLE IF NOT EXISTS "QuizCompletion" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "quizId" TEXT NOT NULL,
    "quizTitle" TEXT NOT NULL,
    "score" INTEGER NOT NULL,
    "totalQuestions" INTEGER NOT NULL,
    "pointsEarned" INTEGER NOT NULL,
    "completedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "QuizCompletion_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "UserReward" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "rewardType" TEXT NOT NULL,
    "points" INTEGER NOT NULL,
    "description" TEXT NOT NULL,
    "earnedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "UserReward_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "UserBadge" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "badgeId" TEXT NOT NULL,
    "badgeName" TEXT NOT NULL,
    "unlockedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "UserBadge_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CRCRCRCRCRCRCRCRCRCRCRCRCRCRCRCRCRCRCRCRCRCuserICRCRCRCRCRCRCRCRCRpletioCRCRCRCRCRCRCRCRCRCRCRCRCndeCRCRCRCRCRCRCRCRCRCRCREXISTSCRCRCRCRCRCRCRCRCRCRCRCRidx" ON "QuizCompletion"("quizId");


RCRCRCRCRCRCRCRCRCRCRCRCRCRCRCRCRCRCISRCRCRCRCRCRCRCRCRCRCRCRCRCRCRCRCdx" ORCRCRCRCRCRCRCRCRCRCRCRCRCRCRCRCRCRCISRCRCRCRCRCRCRCRCRCRCRCRCRCRF NRCRCRCRCRCRCRCRCRCRCRCRCRCRCRCRCRCRCISRCRCRCRCRd"("userId");

-- CreateInde-- CreateInde-- CreateInde-- CreateInded_r-- rdType_idx" ON "UserR-- CreateIwardType");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "UserReward_earnedAt_idx" CREATE INDEX IF NOT EXISt");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "UserBadge_userId_badgeId_key" ON "UserBadge"("userId", "badgeId");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "UserBadge_userId_idx" ON "UserBadge"("userId");
